### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by mrdamaia** [piggly-dev/wc-piggly-pix#1]
Buenas...

Seguinte, fui testar o teu plugin agora pouco e quando chego na finalização da compra ele dá uma mensagem de "Internal Error", dai fui dar uma olhada no log do apache e vi o seguinte:

[Sun Dec 20 17:14:48.681614 2020] [php7:error] [pid 10273] [client 177.82.236.156:59456] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.2.34-8+0~20201103.52+debian9~1.gbpafa084. in /home/mrdamaia/web/MEUSITE.com.br/public_html/wp-content/plugins/pix-por-piggly/vendor/composer/platform_check.php on line 24, referer: https://www.MEUSITE.com.br/wp-admin/admin.php?page=wc-settings&tab=checkout&section=wc_piggly_pix_gateway&screen=testing

O erro fala que o composer requer uma versão do php acima de 7.4 só que a versão do php é 8.0:

php -v
PHP 7.4.13 (cli) (built: Nov 30 2020 20:40:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies

O que estou fazendo de errado?

Valeu pelo plugin!

**Comment by caiquearaujo** [comment]
@mrdamaia Vejo no seu log que você está utilizando a versão 7.2.34-8+020201103.52+debian91.gbpafa084. Existe uma diferença entre a versão cliente e a versão daemon do PHP, okay? Quando você executa o comando `php -v` no console, você está acessando a versão PHP do cliente e não a versão PHP utilizada pelo servidor HTTP. Certifique-se que a sua versão PHP rodando via servidor HTTP (daemon) é a 7.4.

**Comment by caiquearaujo** [comment]
Como não tivemos mais respostas estamos fechando essa issue.
