### ISSUE TITLE
O link de retentativa de pagamento não deveria ir para Aguardando 

### ISSUE THREAD

**Issue by mariovalney** [piggly-dev/wc-piggly-pix#11]
Se o pedido não necessitar pagamento (Aguardando ou algum outro status) o link do template de e-mail não funciona.
`order-pay/XXXX/?pay_for_order=true&key=wc_order_9999`

_De acordo com a discussão nessa issue posso contribuir com código._

**Comment by caiquearaujo** [comment]
Migramos para a função `get_checkout_order_received_url()` que exibe a URL do pedido recebido e exibira o template do Pix se ainda estiver aguardando pagamento.
