### ISSUE TITLE
Erro ao Finalizar Compra - CheckOut

### ISSUE THREAD

**Issue by Welder01** [piggly-dev/wc-piggly-pix#2]
Olá, amigo !

Achei seu plugin fantástico, entretanto, ao finalizar a compra ele não permite gerar o pix, aparece o seguinte erro, que não consta descrição para soluciona-lo, poderia me ajudar?

![screenshot-projetarmed-com-checkout-1608500002649](https://user-images.githubusercontent.com/67652692/102724998-50cc0980-42f2-11eb-8b11-7ee176687dc3.png)

**Comment by caiquearaujo** [comment]
@Welder01 Precisamos do log de erro do PHP para ver o que está acontecendo.

**Comment by caiquearaujo** [comment]
Como não tivemos mais respostas estamos fechando essa issue.
