### ISSUE TITLE
Erro no campo 52 - Merchant Category Cod

### ISSUE THREAD

**Issue by lucasleati** [piggly-dev/wc-piggly-pix#3]
Percebi o seguinte: o campo 52 (Merchant Category Cod) possui tamanho de 4 caracteres, porém está preenchido 00000 (5x o número zero).
Ex.: 520400000

Dessa forma, quando o app do banco lê o QR-Code, ele não preenche o valor fixo informado. Para testar, copiei todo o conteúdo do PIX, removi o 0 a mais, e gerei um QR-code. Dessa forma o valor informado aparece fixo.

**Comment by caiquearaujo** [comment]
@lucasleati Corrigimos esse problema!
