### ISSUE TITLE
Imagem do QR code não aparece no e-mail enviado ao comprador

### ISSUE THREAD

**Issue by fredericofb** [piggly-dev/wc-piggly-pix#4]
![image](https://user-images.githubusercontent.com/76601640/103143111-3f6a6f00-46ef-11eb-90e0-21dbce4344aa.png)

**Comment by caiquearaujo** [comment]
@fredericofb Obrigado pelo feedback, vamos corrigir esse problema!

**Comment by caiquearaujo** [comment]
@fredericofb já corrigimos esse problema!
