### ISSUE TITLE
Erro quando a chave é email

### ISSUE THREAD

**Issue by lucasleati** [piggly-dev/wc-piggly-pix#5]
Percebi o seguinte: quando opto por chave do tipo e-mail, o "@" é removido da chave pix, dando erro na leitura via qr-code e também na chave do copia e cola. Mas copiando a chave completa e inserindo o @, funciona. Em alguma parte do código o @ é removido.  =)

**Comment by caiquearaujo** [comment]
@lucasleati sim, o caractere @ é removido e substituído por um espaço. Isso acontece pois o padrão EMV não permite o caractere @, talvez alguns bancos estejam aceitando apenas com o @. Precisamos saber alguns detalhes como a chave gerada pelo plugin e o banco onde o código tentou ser pago para vermos se está na lista dos bancos testados.

**Comment by caiquearaujo** [comment]
@lucasleati já lançamos uma atualização (a partir da 1.1.0) que corrige esse bug alinhando com a nova versão do Pix. Vamos encerrar essa issue.
