### ISSUE TITLE
Configurações perde os valores / impede salvamento se não estiver completa

### ISSUE THREAD

**Issue by mariovalney** [piggly-dev/wc-piggly-pix#7]
Obrigado pelo plugin.

Quando estamos salvando o erro de validação "Por favor, preencha o campo Chave PIX" impede o salvamento das opções.
É um problema, pois os valores preenchidos se perdem e como há mais de uma seção o usuário espera que a que foi preenchida esteja OK.

Por exemplo, salvando em "Configurações Gerais" o nome da loja.

_De acordo com a discussão nessa issue posso contribuir com código._

**Comment by caiquearaujo** [comment]
Na versão `1.1.14` fizemos esse tratamento da seguinte forma:

- Salva todas as opções, independente do preenchimento da Chave Pix;
- Quando a Chave Pix é preenchida, faz as verificações para os Dados do Pix e salva todo o resto;
- Impede que o plugin seja habilitado até que a Chave Pix seja preenchida.
