### ISSUE TITLE
Página de configurações fora do padrão do WooCommerce

### ISSUE THREAD

**Issue by mariovalney** [piggly-dev/wc-piggly-pix#8]
A página não está seguindo a UI do WooCommerce o que pode causar problemas para usuários leigos.
Há planos para adequar?

_De acordo com a discussão nessa issue posso contribuir com código._

**Comment by caiquearaujo** [comment]
Os templates para o e-mail e para a página de obrigado do Woocommerce foram normalizados. Entretanto, ainda não são templates customizados, ou seja, que não dependem de template pai.

Faremos isso apenas em uma versão Pro do plugin.
