### ISSUE TITLE
Não é possível sobrescrever templates do plugin

### ISSUE THREAD

**Issue by mariovalney** [piggly-dev/wc-piggly-pix#9]
Apesar de estar usando a função "wc_get_template", nenhum caminho é passado, então para sobrescrever os templates do plugin o arquivo deve ir na raiz do "woocommerce".

Isso pode causar conflitos com outros plugins e com o WooCommerce.

**Comment by caiquearaujo** [comment]
A única mudança que farei por aqui é que não é `wc-piggly-pix` a pasta do plugin quando instalado via repositório do Wordpress, mas sim `pix-por-piggly`; Também não deve-se utilizar `woocommerce/` mas sim `WC()->template_path()` dessa forma aumenta a compatibilidade. Além disso, vamos mudar test-settings.php  e main-settings.php para `require_once` ao invés de `wc_get_template`.
